### ISSUE TITLE
Take the Test in upper right corner not working

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#19]
After loading the home page, clicking "Take the Test" in the upper right corner doesn't work.

**Comment by Amcclennahan** [comment]
Consider working on #20 first, as that is higher visibility.

**Comment by noahbrenner** [comment]
For now, #37 (assuming it gets merged) removes the upper right "Take the Test" button so that we're not presenting broken functionality, but that header link (or something like it) should definitely be added back in later. Because of the way our navigation is currently implemented, making that link work on pages other than the home page is a challenge. One idea would be to temporarily fill the gap by linking other pages back to the home page to take the test, but longer term, we should be overhauling our whole front end UI/UX and we can provide a better solution for this as part of that process.

**Comment by csjoblom** [comment]
@noahbrenner I'd recommend extracting that button as component-ize it instead of disabling it completely. Then we can include that component elsewhere until we do a redesign.

**Comment by Amcclennahan** [comment]
Looks like we ended up removing this button. I'll close this ticket but we can reopen/make a new ticket if we'd like to revisit it at a later date

**Comment by noahbrenner** [comment]
Sounds good. I think the plan is to add that feature back in when we redo the front end in a sane way. With the way the site (and specifically the test) currently works, it would take a lot to get such a link working from any page other than the home page (which would be the only point, since the home page already has a prominent button for that).
