### ISSUE TITLE
Take the Test in center of homepage "enables" inconsistently

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#20]
Investigate why the button isn't enabled at the start (probably intentional, we need to understand why) and then look into why it may not load consistently.

**Comment by noahbrenner** [comment]
### Some background

* When the home page first loads, the "Take the Test!!" button is disabled by default via the HTML served.
* The button is only enabled after issuing an XHR to an endpoint on our server and receiving the response. This request is only sent when the page first loads because it's called from a DOMContentLoaded listener. We'd prefer not to have that delay before the button is enabled.
* When the user clicks the now-enabled button, the page is updated to show the form for taking the speed test, but the URL does not change.
* If the user clicks the browser's Back button, the "Take the Test!!", the emulated navigation correctly returns to the home page, but the button remains disabled forever.
* Similarly, if the user navigates from the home page to *any* other page and then back using the top left "SpeedUpAmerica" link, the button is never enabled.

### The current (simplified) call stack

All functions named here are defined in `app/assets/javascripts/home.coffee`. The function referred to in each bullet point is where the next point is executed:

* When the page loads, a DOMContentLoaded listener is added via jQuery.
* If we're on the home page (`window.location.pathname == '/'`), `get_location()` is called.
* If geolocation is supported, the current position is retrieved and passed to `set_coords()`.
* An AJAX request is sent to our server's `/home/get_location_data` JSON endpoint and a listener is defined to handle a successful request.
* The received values are used to update some hidden form fields and **The "Take the Test!!" button is enabled**.

### Likely solution

It looks like we can fairly cleanly call `get_location()` either when the user clicks the "Take the Test!!" button or maybe as the form that actually *runs* the test is submitted. I still need to take a closer look and try it out.

### Other idiosyncrasies

There is a function called [start_speed_test](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/assets/javascripts/home.coffee#L69) which sets a click listener on DOM elements with the `test-speed-btn` class. There are 3 such elements, but none of them are visible when visiting the homepage or after clicking the "Take the Test!!" button.

I'm wondering if these are left over from a previous implementation. We may be able to delete this function entirely as well as the elements it sets listeners for. If we *do* keep this function, I'd want to rename it to `enable_speed_test` since it only sets listeners, it doesn't actually kick off the test itself.

**Comment by ryanrolds** [comment]
Yeah, remove that logic. When they agree to give us access to their location lets enable the button (or however it works). As they are taking the test we can get more accurate location information. Make sure to also use [watchPosition(...)](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#Watching_the_current_position) we can get the most accurate location we can. We will use whatever location we have when they submit. 

If for some reason we don't have a point when they submit their speed test we will probably need to wait until we do or error after some period of time (30 seconds?).

**Comment by Amcclennahan** [comment]
I've created #28 and #29 to break this up a little bit. That said, Is there anything here that is needed to be done aside from those two things?

If not, let's get this bad boy closed and move to the other, more granular tickets @noahbrenner

**Comment by noahbrenner** [comment]
Closing this now, since the original issue was solved by #37.
The issue for using `watchPosition()` instead of `getCurrentPosition()` is in it's own ticket, #28, and more broadly in #29.
